-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.paises
(
    id_pais integer NOT NULL,
    nombre_pais text COLLATE pg_catalog."default",
    CONSTRAINT paises_pkey PRIMARY KEY (id_pais)
);

CREATE TABLE IF NOT EXISTS public.personas
(
    id_persona integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre_persona text COLLATE pg_catalog."default" NOT NULL,
    nacimiento_persona date NOT NULL,
    id_pais integer,
    CONSTRAINT personas_pkey PRIMARY KEY (id_persona)
);

ALTER TABLE IF EXISTS public.personas
    ADD CONSTRAINT id_pais FOREIGN KEY (id_pais)
    REFERENCES public.paises (id_pais) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS fki_id_pais
    ON public.personas(id_pais);

END;